#!/bin/sh
echo "${PWD}/raw/array/ffi-hs-array.agda-lib"
echo "${PWD}/raw/base/ffi-hs-base.agda-lib"
echo "${PWD}/raw/bytestring/ffi-hs-bytestring.agda-lib"
echo "${PWD}/raw/containers/ffi-hs-containers.agda-lib"
echo "${PWD}/raw/dear-imgui/ffi-hs-dear-imgui.agda-lib"
echo "${PWD}/raw/deepseq/ffi-hs-deepseq.agda-lib"
echo "${PWD}/raw/exceptions/ffi-hs-exceptions.agda-lib"
echo "${PWD}/raw/linear/ffi-hs-linear.agda-lib"
echo "${PWD}/raw/primitive/ffi-hs-primitive.agda-lib"
echo "${PWD}/raw/scientific/ffi-hs-scientific.agda-lib"
echo "${PWD}/raw/sdl2/ffi-hs-sdl2.agda-lib"
echo "${PWD}/raw/StateVar/ffi-hs-StateVar.agda-lib"
echo "${PWD}/raw/stm/ffi-hs-stm.agda-lib"
echo "${PWD}/raw/text/ffi-hs-text.agda-lib"
echo "${PWD}/raw/unliftio-core/ffi-hs-unliftio-core.agda-lib"
echo "${PWD}/raw/vector/ffi-hs-vector.agda-lib"
